---
- name: Find the closes apache mirror
  shell: "curl 'https://www.apache.org/dyn/closer.cgi' |  grep -o '<strong>[^<]*</strong>' | sed 's/<[^>]*>//g' | head -1"
  register: apache_mirror
  changed_when: false

- name: Fetch kafka binary package
  get_url: dest="{{ kafka_tarball_location }}/{{ kafka_tarball_name }}" url="{{apache_mirror.stdout}}/kafka/{{kafka_version}}/{{kafka_tarball_name}}"
